version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data
      - ./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    env_file:
      - docker.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 2s
      retries: 5


  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - docker.env
    depends_on:
      db:
        condition: service_healthy
    image: quasit/home_budget