apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - protocol: TCP
    port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
          #valueFrom:
          #  secretKeyRef:
          #    name: postgres-secret
          #    key: postgres-username
        - name: POSTGRES_PASSWORD
          value: postgres
          #valueFrom:
          #  secretKeyRef:
          #    name: postgres-secret
          #    key: postgres-password
        - name: POSTGRES_DB
          value: home_budget
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim